version: '3.8'
services:
  jupyter-book:
    image: jbook
    volumes:
      - .:/home/
    # command: jupyter-book toc migrate /home/_toc.yml -o /home/_toc.yml
    command: jupyter-book build /home/
    restart: always

  httpd:
    image: httpd:latest
    volumes:
      - ./_build/html/:/usr/local/apache2/htdocs/
    restart: always
    ports:
      - "${HOST}:8012:80"